import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Theme } from '@radix-ui/themes';
import { Header } from '@/app/layout/header';
import { Sidebar } from '@/app/layout/sidebar';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className="dark ">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen `}
      >
        <Theme>
          <Header />
          <div className="flex flex-row w-screen gap-4 p-4 overflow-hidden container mx-auto relative">
            <Sidebar className="z-50  w-14 hover:w-52 transition-all duration-1000 overflow-x-hidden bg-slate-900/50  rounded-l border-slate-700/50 border-2 h-120  " />
            {children}
          </div>
        </Theme>
      </body>
    </html>
  );
}
