import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import { Header } from "@/app/layout/header";
import { Sidebar } from "@/app/layout/sidebar";
import { ParticleEffect } from "./dashboard/components/particle-effect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className="dark ">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen `}
      >
        <Theme>
          <div className="flex flex-col gap-2 py-4 container mx-auto">
            <Header />
            <div className="flex flex-row gap-2">
              <Sidebar />
              {children}
            </div>
          </div>
        </Theme>
      </body>
    </html>
  );
}
